---
version: '3.7'

services:
  keycloak:
    image: jboss/keycloak:{{ keycloak_version }}
    container_name: keycloak
    restart: unless-stopped
    volumes:
      - ./standalone.xml:{{ jboss_home }}/standalone/configuration/standalone.xml
      - ./realm-export.json:{{ keycloak_import }}
      - ./patternfly/:/opt/jboss/keycloak/themes/patternfly/
    environment:
      - KEYCLOAK_USER={{ keycloak_admin_username }}
      - KEYCLOAK_PASSWORD={{ keycloak_admin_password }}
      - KEYCLOAK_IMPORT={{ keycloak_import }}
      - DB_ADDR={{ pg_hostname }}
      - DB_PORT={{ pg_port }}
      - DB_DATABASE={{ keycloak_database_name }}
      - DB_SCHEMA=public
      - DB_USER={{ keycloak_admin_username }}
      - DB_PASSWORD={{ keycloak_admin_password }}
      - DB_VENDOR=postgres
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - '8080:8080'
      - '8443:8443'
    networks:
      - sm_network

networks:
  sm_network:
    external: true