- name: Copy template files
  template:
    src: '{{ item }}'
    dest: '{{ docker_compose_dir }}/postgres/{{ item }}'
    mode: 0600
  loop:
    - 00_setup_db.sql
    - docker-compose.yml
    - Dockerfile
  register: compose_config

- name: Start the containers
  docker_compose:
    project_src: '{{ docker_compose_dir }}/postgres'
    restarted: '{{ compose_config is changed }}'
    build: yes
    state: present