version: '2'
services:
  memcached:
    image: {{ memcached_image }}:{{ memcached_version }}
    container_name: awx_memcached
    restart: unless-stopped
    environment:
      http_proxy: {{ http_proxy | default('') }}
      https_proxy: {{ https_proxy | default('') }}
      no_proxy: {{ no_proxy | default('') }}
    networks:
      - sm_network

  rabbitmq:
    image: {{ rabbitmq_image }}
    container_name: awx_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: {{ rabbitmq_default_vhost }}
      RABBITMQ_DEFAULT_USER: {{ rabbitmq_user }}
      RABBITMQ_DEFAULT_PASS: {{ rabbitmq_password | quote }}
      RABBITMQ_ERLANG_COOKIE: {{ rabbitmq_erlang_cookie }}
    networks:
      - sm_network

  web:
    image: '{{ awx_web_image }}'
    container_name: {{ awx_web_host }}
    depends_on:
      - rabbitmq
      - memcached
    hostname: {{ awx_web_host }}
    user: root
    ports:
      - "8052:8052"
    restart: unless-stopped
    volumes:
      - "{{ docker_compose_dir }}/awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "{{ docker_compose_dir }}/awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "{{ docker_compose_dir }}/awx/credentials.py:/etc/tower/conf.d/credentials.py"
      - "{{ project_data_dir }}:/var/lib/awx/projects/sm-playbooks:rw"
    environment:
      DATABASE_USER: {{ pg_admin_username }}
      DATABASE_PASSWORD: {{ pg_admin_password }}
      DATABASE_NAME: {{ awx_database_name }}
      DATABASE_PORT: {{ pg_port }}
      DATABASE_HOST: {{ pg_hostname }}
    networks:
      - sm_network

  task:
    image: {{ awx_task_image }}
    container_name: {{ awx_task_host }}
    depends_on:
      - rabbitmq
      - memcached
      - web
    hostname: {{ awx_task_host }}
    user: root
    restart: unless-stopped
    volumes:
      - "{{ docker_compose_dir }}/awx/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "{{ docker_compose_dir }}/awx/environment.sh:/etc/tower/conf.d/environment.sh"
      - "{{ docker_compose_dir }}/awx/credentials.py:/etc/tower/conf.d/credentials.py"
      - "{{ project_data_dir }}:/var/lib/awx/projects/sm-playbooks:rw"
    environment:
      DATABASE_USER: {{ pg_admin_username }}
      DATABASE_PASSWORD: {{ pg_admin_password }}
      DATABASE_NAME: {{ awx_database_name }}
      DATABASE_PORT: {{ pg_port }}
      DATABASE_HOST: {{ pg_hostname }}
    networks:
      - sm_network

networks:
  sm_network:
    external: true