version: '2'
services:
  postgres:
    image: {{ project_name }}/postgres:{{ pg_version }}
    build: {{ docker_compose_dir }}/postgres
    restart: unless-stopped
    container_name: postgres
#   volumes:
#    - postgres-volume:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: {{ pg_admin_password }}
      POSTGRES_USER: {{ pg_admin_username }}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - sm_network

networks:
  sm_network:
    external: true