- name: Copy template files
  template:
    src: '{{ item }}'
    dest: '{{ docker_compose_dir }}/proxy/{{ item }}'
    mode: 0600
  loop:
    - nginx.conf
    - proxy.conf
    - docker-compose.yml
  register: compose_config

- name: Copy files
  copy:
    src: '{{ item }}'
    dest: '{{ docker_compose_dir }}/proxy/{{ item }}'
    mode: 0600
  loop:
    - favicon.ico

- name: Start the containers
  docker_compose:
    project_src: '{{ docker_compose_dir }}/proxy'
    restarted: '{{ compose_config is changed }}'
    build: yes
    state: present