- name: Copy template files
  template:
    src: '{{ item }}'
    dest: '{{ docker_compose_dir }}/keycloak/{{ item }}'
    mode: 0776
  loop:
    - docker-compose.yml
    - standalone.xml
    - realm-export.json
  register: keycloak_compose_config

- name: Copy patternfly theme
  copy:
    src: '{{ item }}'
    dest: '{{ docker_compose_dir }}/keycloak/{{ item }}'
  loop:
    - patternfly

- name: Start the containers
  docker_compose:
    project_src: '{{ docker_compose_dir }}/keycloak'
    restarted: '{{ keycloak_compose_config is changed }}'
    build: yes
    state: present
  register: keycloak_compose_start