---
- name: Create the project
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - ./secret.yml
  vars:
    state: present
  roles:
    - assert_requirements
    - setup_project
#   - letsencrypt
    - run_db
    - run_awx
    - run_keycloak
    - run_api
    - run_dashboard
    - run_proxy