---
- name: Create the project
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - ./secret.yml
    - ./version.ini
  vars:
    state: present
  roles:
    - run_awx
    - run_keycloak
    - run_api
    - run_dashboard
    - run_proxy