- name: Get last version
  include_vars: "{{ inventory_dir }}/version.ini"

- name: Log into DockerHub
  docker_login:
    username: '{{ dockerhub_user }}'
    password: '{{ dockerhub_password }}'

- name: Build images with version
  docker_image:
    name: 'conatelid/{{ project_name }}-{{ item }}-prod:{{ version }}'
    push: yes
    source: local
  loop:
    - api
    - dashboard