version: '3'
services:
  proxy:
    image: nginx:1.15.1
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./favicon.ico:/etc/nginx/favicon.ico
      - {{ certificates_folder }}/{{ public_domain }}.crt:/etc/nginx/{{ public_domain }}.crt
      - {{ certificates_folder }}/{{ public_domain }}.key:/etc/nginx/{{ public_domain }}.key
    ports:
{% if env == 'dev' %}
      - "80:80"
{% else %}
      - '443:443'
{% endif %}
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - sm_network

networks:
  sm_network:
    external: true